services:
  app:
    container_name: faq_api
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis
    environment:
      - COREPACK_DEFAULT_TO_LATEST=0
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/faqs
      - REDIS_URI=redis://redis:6379
      - JWT_SECRET=${JWT_SECRET}
    env_file:
      - ./.env
    networks:
      - faq_api

  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - faq_api

  redis:
    image: redis:latest
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - faq_api

volumes:
  mongo_data:
    name: faq_mongo_data
  redis_data:
    name: faq_redis_data

networks:
  faq_api: