version: '3.8'

services:
  app:
    build: .
    container_name: faq_api
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/faqs
      - REDIS_URI=redis://redis:6379
      - JWT_SECRET=${JWT_SECRET}
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules

  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  redis:
    image: redis:latest-alpine
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

volumes:
  mongo_data:
    name: faq_mongo_data
  redis_data:
    name: faq_redis_data
